import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Brain, TrendingUp, AlertTriangle, CheckCircle } from "lucide-react"

interface AIAnalysisProps {
  analysis: string
}

export function AIAnalysis({ analysis }: AIAnalysisProps) {
  // Mock AI insights - in a real app, this would come from AI analysis
  const insights = [
    {
      type: "strength",
      icon: CheckCircle,
      title: "Strong Architecture",
      description: "Well-structured React components with proper separation of concerns",
    },
    {
      type: "improvement",
      icon: TrendingUp,
      title: "Performance Opportunity",
      description: "Consider implementing code splitting and lazy loading",
    },
    {
      type: "warning",
      icon: AlertTriangle,
      title: "Accessibility Gap",
      description: "Missing ARIA labels and keyboard navigation support",
    },
  ]

  const getInsightColor = (type: string) => {
    switch (type) {
      case "strength":
        return "text-green-600 bg-green-50 border-green-200"
      case "improvement":
        return "text-blue-600 bg-blue-50 border-blue-200"
      case "warning":
        return "text-orange-600 bg-orange-50 border-orange-200"
      default:
        return "text-gray-600 bg-gray-50 border-gray-200"
    }
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-lg">
          <Brain className="w-5 h-5" />
          AI Analysis
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="p-3 bg-muted/50 rounded-lg">
          <p className="text-sm leading-relaxed">{analysis}</p>
        </div>

        <div className="space-y-3">
          <h4 className="font-medium text-sm">Key Insights</h4>
          {insights.map((insight, index) => {
            const Icon = insight.icon
            return (
              <div key={index} className={`p-3 rounded-lg border ${getInsightColor(insight.type)}`}>
                <div className="flex items-start gap-2">
                  <Icon className="w-4 h-4 mt-0.5 flex-shrink-0" />
                  <div>
                    <div className="font-medium text-sm">{insight.title}</div>
                    <div className="text-xs mt-1 opacity-80">{insight.description}</div>
                  </div>
                </div>
              </div>
            )
          })}
        </div>

        <div className="pt-2 border-t">
          <div className="flex items-center justify-between text-xs text-muted-foreground">
            <span>Analysis generated by AI</span>
            <Badge variant="outline" className="text-xs">
              Beta
            </Badge>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}
